name: aws_lambda_deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLOUDWATCH_LAMBDA_SLACK_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CLOUDWATCH_LAMBDA_SLACK_ACCESS_SECRET }}
          aws-region: ap-south-1
      - name: Serverless Deploy
        run: npm run-script deploy